{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight-fabric",
    "version": "1.19.2-2.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-fabric-1.19.2-2.1.5-fabric.jar",
          "url": "moonlight-fabric-1.19.2-2.1.5-fabric.jar",
          "size": 739365,
          "sha512": "6a97c3d1caff738029edae0516eaad06c10b2b6111691336e01eea79598d3612002b0965b06c67213ad67519c63359caa12b6e1698a4a94e46c55b67095a7422",
          "sha256": "20b019150b67cb22eb5a50726e95d3118a09fed29134983198982fc55c72421c",
          "sha1": "916372a427d42927bc95dc0e58df497c1dcd16a0",
          "md5": "bdf397cb0b4e3d878a384cc66eabc2d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "7.0.72"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "map-atlases-436298",
          "version": {
            "requires": "3953555"
          }
        },
        {
          "group": "curse.maven",
          "module": "yacl-667299",
          "version": {
            "requires": "3987709"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-fabric-1.19.2-2.1.5-fabric.jar",
          "url": "moonlight-fabric-1.19.2-2.1.5-fabric.jar",
          "size": 739365,
          "sha512": "6a97c3d1caff738029edae0516eaad06c10b2b6111691336e01eea79598d3612002b0965b06c67213ad67519c63359caa12b6e1698a4a94e46c55b67095a7422",
          "sha256": "20b019150b67cb22eb5a50726e95d3118a09fed29134983198982fc55c72421c",
          "sha1": "916372a427d42927bc95dc0e58df497c1dcd16a0",
          "md5": "bdf397cb0b4e3d878a384cc66eabc2d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-fabric-1.19.2-2.1.5-sources.jar",
          "url": "moonlight-fabric-1.19.2-2.1.5-sources.jar",
          "size": 415671,
          "sha512": "cf16ee6b7610fe25c75a344fa299c941271ec330faf2272c2a9891a1915dbbcc5de63623c6cc56554f33e791d0a8c173ae44454068bb5f6f505ac8d4a0c9cf17",
          "sha256": "d365030e75919e3609aaf874c629f09705a1c837982cda5bc87d6c9d494e9a72",
          "sha1": "03d4f55996f759b550b50ca72551ae6c18ebf33b",
          "md5": "e48200c0a38159908379ee9890769e9a"
        }
      ]
    }
  ]
}
