name: Report Bug
description: Found a bug? Report it.
title: "[🐞]: "
labels: "bug"

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        ### Before Submitting
        Please ensure that:

        - You are using the latest version of the mod and its dependencies
        - You have attached `latest.log` if the game is crashing
        - You removed unsupported mods (Optifine, hybrid servers like Mohist/Velocity, Fabric API on Forge, etc.)
        - You tested by isolating the issue (disable mods and re-enable 1–2 at a time)
        - You searched existing issues to avoid duplicates

        Failure to follow these steps may result in the issue being closed.

  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I have read and followed the steps above.
          required: true

  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: Select the Minecraft version and loader.
      options:
        - 1.21.1-NEOFORGE
        - 1.21.1-FABRIC
        - 1.20.1-FORGE
        - 1.20.1-FABRIC
        - 1.19.2-FORGE
        - 1.18.2-FORGE
      default: 0
    validations:
      required: true

  - type: input
    id: supplementaries
    attributes:
      label: Supplementaries Version
      description: Full mod version string.
      placeholder: ex. supplementaries-1.20-2.7.33
    validations:
      required: true

  - type: textarea
    id: issue-details
    attributes:
      label: Describe the Issue
      description: Provide a clear and concise description.
      placeholder: |
        Steps to reproduce:

        Always attach the `latest.log` file from /logs.
    validations:
      required: true
